### ISSUE TITLE
getClientset alternative

### ISSUE THREAD

**Issue by StevenACoffman** [gkarthiks/k8s-discovery#28]
Hi! I have been happily using your library, and I ran across a very succinct alternative that also works in a pod in a cluster and outside a cluster that you might want to use in your library. From [Lars Ekman](https://kubernetes.slack.com/archives/C09R23FHP/p1626285472150100?thread_ts=1626275729.149400&cid=C09R23FHP):
```
func getClientset() (*kubernetes.Clientset, error) {
        config, err := rest.InClusterConfig()
        if err != nil {
                kubeconfig :=
                        clientcmd.NewDefaultClientConfigLoadingRules().GetDefaultFilename()
                config, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
                if err != nil {
                        return nil, err
                }
        }
        return kubernetes.NewForConfig(config)
}
```

**Comment by gkarthiks** [comment]
This is cool. I will definitely consider this @StevenACoffman. Thank you so much.
